name: Package

on: workflow_dispatch




jobs:
  build:
    name: ${{ matrix.platform.name }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: 'Linux (x64)'   ,os: ubuntu-latest               }
          - { name: 'Windows (x64)' ,os: windows-latest              }
          - { name: 'Mac (x64)'     ,os: macos-latest                }
          - { name: 'Mac (arm64)'   ,os: macos-latest   ,arch: arm64 }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v4

      - run: >
          npm i
          npm run package

      - uses: actions/upload-artifact@v4
        with:
          path: dist
